/// ===== LESSON TITLES =====
/// 10 chapters × 9 lessons each
/// Example: lessonTitles[0][0] = "How do AI learn?"
const List<List<String>> lessonTitles = [
  [
    "How do AI learn?",
    "Data: The Fuel of AI",
    "Supervised vs Unsupervised Learning",
    "Training vs Inference",
    "Overfitting and Underfitting",
    "Loss Functions Explained",
    "Gradient Descent Basics",
    "Bias and Variance Tradeoff",
    "Evaluation Metrics (Accuracy, Precision, Recall)",
  ],
  [
    "Linear Regression — The First Model",
    "Logistic Regression and Classification",
    "Decision Trees and Splitting Rules",
    "Random Forests and Bagging",
    "Support Vector Machines",
    "Naive Bayes Classifier",
    "K-Nearest Neighbors",
    "Clustering with K-Means",
    "Dimensionality Reduction (PCA)",
  ],
  [
    "What is a Neural Network?",
    "Perceptrons and Activation Functions",
    "Feedforward Neural Networks",
    "Backpropagation Explained",
    "Optimization with SGD & Adam",
    "Regularization (Dropout, L2)",
    "Batch Normalization",
    "Vanishing & Exploding Gradients",
    "Deep vs Shallow Networks",
  ],
  [
    "Convolutional Neural Networks (CNNs)",
    "How Filters Detect Features",
    "Pooling Layers",
    "Image Classification with CNNs",
    "Transfer Learning",
    "Data Augmentation",
    "Object Detection Basics",
    "Segmentation (U-Net)",
    "Vision Transformers",
  ],
  [
    "Sequence Models (RNNs)",
    "Vanilla RNN Limitations",
    "Long Short-Term Memory (LSTMs)",
    "Gated Recurrent Units (GRUs)",
    "Attention Mechanism",
    "Transformers — The Game Changer",
    "Encoder-Decoder Models",
    "BERT and Masked Language Models",
    "GPT and Autoregressive Models",
  ],
  [
    "Natural Language Processing Overview",
    "Text Preprocessing (Tokenization, Stemming)",
    "Word Embeddings (Word2Vec, GloVe)",
    "Contextual Embeddings",
    "Sentiment Analysis",
    "Named Entity Recognition",
    "Question Answering Systems",
    "Machine Translation",
    "Summarization Techniques",
  ],
  [
    "Reinforcement Learning Basics",
    "Markov Decision Processes",
    "Exploration vs Exploitation",
    "Value Iteration & Policy Iteration",
    "Q-Learning",
    "Deep Q-Networks (DQNs)",
    "Policy Gradient Methods",
    "Actor-Critic Algorithms",
    "Applications of RL (Games, Robotics)",
  ],
  [
    "Generative Models Overview",
    "Autoencoders",
    "Variational Autoencoders (VAEs)",
    "Generative Adversarial Networks (GANs)",
    "Conditional GANs",
    "Diffusion Models",
    "Stable Diffusion",
    "Style Transfer",
    "Text-to-Image Generation",
  ],
  [
    "AI Ethics and Fairness",
    "Bias in Data and Models",
    "Interpretability and Explainability",
    "Privacy-Preserving ML (Federated Learning)",
    "Adversarial Attacks",
    "Robustness in AI Systems",
    "Responsible Deployment",
    "AI and the Law",
    "The Future of Ethical AI",
  ],
  [
    "AI in the Real World",
    "Recommendation Systems",
    "Search and Ranking Algorithms",
    "Fraud Detection",
    "Healthcare Applications of AI",
    "Autonomous Vehicles",
    "AI in Finance",
    "Robotics and Control",
    "The Future of Artificial General Intelligence",
  ],
];
